### ISSUE TITLE
Testing on Windows

### ISSUE THREAD

**Issue by pastak** [pastak/gyazo-menubar#2]
Check running correctly
- [ ] Windows 10
- [ ] Windows 8 
- [ ] Windows 7

**Comment by terepanda** [comment]
https://www.dropbox.com/s/qbrzdyh8ggkw1wc/Gyazo-Menubar-win32.zip?dl=0
をダウンロードさせていただきましたが、当方のWindows 8.1環境では下記のエラーが出て起動しませんでした。
エラーダイアログを閉じても Gyazo-Menubar.exe というプロセスが2つ残りますが、ツールバーにアイコンなどは表示されませんでした。
![default](https://cloud.githubusercontent.com/assets/1763675/10133208/8c48c87c-6616-11e5-8256-b9a41e88b62b.PNG)
Uncaught Exception:
Error: Cannot find module 'menubar'
    at Function.Module._resolveFilename (module.js:324:15)
    at Function.Module._load (module.js:266:25)
    at Module.require (module.js:353:17)
    at require (module.js:372:17)
    at Object.<anonymous> (C:\Gyazo-Menubar-win32\resources\app\app.js:4:15)
    at Module._compile (module.js:418:26)
    at Object.Module._extensions..js (module.js:436:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:298:12)
    at Object.<anonymous> (C:\Gyazo-Menubar-win32\resources\atom.asar\browser\lib\init.js:104:10)

**Comment by pastak** [comment]
@terepanda さんありがとうございます。

最新のものをビルドしたので、 https://github.com/pastak/gyazo-menubar/releases からDLして試してみてもらえますか？

**Comment by terepanda** [comment]
@pastak さん ありがとうございます:smile:
https://github.com/pastak/gyazo-menubar/releases/download/v0.0.3/Gyazo-Menubar-win32-ia32.zip
https://github.com/pastak/gyazo-menubar/releases/download/v0.0.3/Gyazo-Menubar-win32-x64.zip
を試させていただきました。
今度はきちんと起動したのですが、最初にGyazoにログインして認証を許可した後は、トレイアイコンを左クリックすると真っ黒のポップアップが表示されて、画像は表示されませんでした。（この部分に自分のGyazoに保存された画像が表示されるのですよね？）黒いポップアップウィンドウの内側のいろいろな場所を左クリックしたり、右クリックしてみましたが、クリップボードへの画像コピーもコンテキストメニューの表示も起きませんでした。黒いポップアップ以外の場所をクリックすれば自動的にポップアップは閉じます。

ちなみに終了方法がわからなかったので、タスクマネージャから強制終了しました。トレイアイコンを右クリックしても何も反応しませんでしたが、もしかすると本来は右クリックから終了できるのでしょうか？

念のため、タスクバーの位置も変えて試してみましたが、いずれの場合も画像は表示されませんでした。
タスクバーを画面の下に表示
![7175ff990fe1475342b267f2f2214729 1](https://cloud.githubusercontent.com/assets/1763675/10169777/a080f75e-670d-11e5-97c2-e7330858dcc9.png)

タスクバーを画面の左に表示
![09b7708d626887869b4042e9d4a7a611 1](https://cloud.githubusercontent.com/assets/1763675/10169843/edd539ac-670d-11e5-82c3-212b26a215a5.png)

タスクバーを画面の上に表示
![c089da8a4e8abe01b2c9ae1b3c163b64 1](https://cloud.githubusercontent.com/assets/1763675/10169884/138ea07a-670e-11e5-84ed-a93406301010.png)

タスクバーを画面の右に表示
![e83f6deb411d205bde70a0488545bffb 1](https://cloud.githubusercontent.com/assets/1763675/10170043/64c95d18-670e-11e5-8f17-e69960953ab3.png)

お手すきの時にでもご確認いただけると嬉しいです。:panda_face::relaxed:

**Comment by pastak** [comment]
@terepanda さん、丁寧にありがとうございます。 :bow: 

そういや、タスクバーに常駐することを考えていたので終了手段を考えてませんでした。。。 :cry: 

表示されない件も了解しました。かなり重要な感じなので早めに直します
